#!/usr/local/bin/expect

set moduleName [lindex $argv 0]
set moduleDir  [lindex $argv 1]
set user       "gosunyun"
set password   "gsy2017"
# set user       "gaussian"
# set password   "gxx"
set ip         "10.7.5.220"
# set ip         "192.168.42.184"
# set ip         "192.168.42.111"

set timeout -1

spawn scp $moduleName $user@$ip:/home/Node/$moduleDir
expect {
    "(yes/no)?"
    {send "yes\n";exp_continue}
    "password:"
    {send "$password\n"}
}
expect eof
