app:httpTest.cpp
	g++ httpTest.cpp -o app -lboost_system -lboost_filesystem -lboost_regex -std=c++11 -pthread -I./include/HttpLib -L./Libs -I./include/boost-1.65.0  -Wl,-rpath=./Libs


clean:
	rm -f app
